services:
  optiguide:
    build: .
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:8080/auth/google/callback
      - SESSION_SECRET=${SESSION_SECRET}
      - POSTGRES_USER=optiguide
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=optiguide
      - POSTGRES_HOST=postgres
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine3.20
    environment:
      - POSTGRES_USER=optiguide
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=optiguide
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U optiguide"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:
volumes:
  postgres_data:
